import { SupplierListPage } from "@/features/supplier-list-page/supplier-list-page";
import Head from "next/head";

export default function SupplierList() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SupplierListPage />
    </>
  );
}
