import { EditSupplierPage } from "@/features";
import Head from "next/head";
import { useRouter } from "next/router";

export default function EditSupplier() {
  const { query } = useRouter();

  const supplierId = query.id;
  if (typeof supplierId !== "string") {
    return <div></div>;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <EditSupplierPage supplierID={supplierId} />
    </>
  );
}
